/**
 * Convertisseur Bitpanda : franchissement du préambule de 6 lignes (détection sur la ligne
 * d'avertissement, retrouve la vraie ligne d'en-tête), `-` comme valeur nulle, achat, vente,
 * dépôt (montant net de frais, brut = net + frais), retrait, transfert interne, ligne hors
 * périmètre crypto (Stock), type inconnu et timestamp ISO à décalage explicite illisible.
 */
import { describe, expect, it } from 'vitest';
import { bitpanda, parseIsoOffsetToMs } from './bitpanda';
import { importAnyCsv } from './index';
import { parseCsvText } from '../csv';

const USD_RATE = (): string => '1.1';
const FOREIGN_HEADER = ['Timezone', 'Date', 'Time', 'Type', 'Currency', 'Amount'];

// Préambule 100 % inventé (structure décrite par la spec : avertissement, titulaire, e-mail, date
// d'ouverture, Venue, Reported by) — le texte exact d'un fichier réel n'a pas été observé.
const PREAMBLE = [
  'This document was automatically generated by Bitpanda and is provided for information only.',
  'Verified Account Holder: Jane Doe',
  'Email: jane.doe@example.com',
  'Account Opening Date: 2020-01-15',
  'Venue: Bitpanda',
  'Reported by Bitpanda GmbH',
];

const HEADER = [
  'Transaction ID',
  'Timestamp',
  'Transaction Type',
  'In/Out',
  'Amount Fiat',
  'Fiat',
  'Amount Asset',
  'Asset',
  'Asset market price',
  'Asset market price currency',
  'Asset class',
  'Product ID',
  'Fee',
  'Fee asset',
  'Spread',
  'Spread Currency',
];

const ROWS: string[][] = [
  // Achat : jambe fiat envoyée, jambe crypto reçue, frais EUR.
  [
    'BP1',
    '2026-03-02T09:14:02+01:00',
    'buy',
    'outgoing',
    '502',
    'EUR',
    '0.01',
    'BTC',
    '50000',
    'EUR',
    'Cryptocurrency',
    '-',
    '2',
    'EUR',
    '1.5',
    'EUR',
  ],
  // Vente : jambe crypto envoyée, jambe fiat reçue.
  [
    'BP2',
    '2026-03-03T10:00:00+01:00',
    'sell',
    'incoming',
    '305',
    'EUR',
    '0.005',
    'BTC',
    '61000',
    'EUR',
    'Cryptocurrency',
    '-',
    '1.5',
    'EUR',
    '0.8',
    'EUR',
  ],
  // Dépôt fiat net de frais : brut = 998 + 2 = 1000 EUR.
  [
    'BP3',
    '2026-03-04T08:00:00+01:00',
    'deposit',
    'incoming',
    '998',
    'EUR',
    '-',
    '-',
    '-',
    '-',
    'Fiat',
    '-',
    '2',
    'EUR',
    '-',
    '-',
  ],
  // Retrait crypto, frais réseau en ETH.
  [
    'BP4',
    '2026-03-05T08:00:00+01:00',
    'withdrawal',
    'outgoing',
    '-',
    '-',
    '0.2',
    'ETH',
    '3000',
    'EUR',
    'Cryptocurrency',
    '-',
    '0.001',
    'ETH',
    '-',
    '-',
  ],
  // Transfert : mouvement interne (hypothèse assumée, voir bitpanda.ts).
  [
    'BP5',
    '2026-03-06T08:00:00+01:00',
    'transfer',
    'outgoing',
    '-',
    '-',
    '0.05',
    'ETH',
    '-',
    '-',
    'Cryptocurrency',
    '-',
    '-',
    '-',
    '-',
    '-',
  ],
  // Type inconnu.
  [
    'BP6',
    '2026-03-07T08:00:00+01:00',
    'foobar',
    'outgoing',
    '-',
    '-',
    '0.01',
    'BTC',
    '-',
    '-',
    'Cryptocurrency',
    '-',
    '-',
    '-',
    '-',
    '-',
  ],
  // Hors périmètre : action, pas crypto ni fiat.
  [
    'BP7',
    '2026-03-08T08:00:00+01:00',
    'buy',
    'incoming',
    '100',
    'EUR',
    '1',
    'AAPL',
    '100',
    'EUR',
    'Stock (derivative)',
    'PID1',
    '0.5',
    'EUR',
    '-',
    '-',
  ],
  // Timestamp illisible.
  [
    'BP8',
    'not-a-timestamp',
    'buy',
    'incoming',
    '100',
    'EUR',
    '0.001',
    'BTC',
    '-',
    '-',
    'Cryptocurrency',
    '-',
    '-',
    '-',
    '-',
    '-',
  ],
];

const CSV = [...PREAMBLE, HEADER.join(','), ...ROWS.map((r) => r.join(','))].join('\n');

describe('parseIsoOffsetToMs', () => {
  it('convertit un décalage explicite (ou Z) et rejette les formes invalides', () => {
    expect(parseIsoOffsetToMs('2026-03-02T09:14:02+01:00')).toBe(Date.UTC(2026, 2, 2, 8, 14, 2));
    expect(parseIsoOffsetToMs('2026-03-02T09:14:02Z')).toBe(Date.UTC(2026, 2, 2, 9, 14, 2));
    expect(parseIsoOffsetToMs('2026-13-02T09:14:02+01:00')).toBeNull();
    expect(parseIsoOffsetToMs('not-a-timestamp')).toBeNull();
  });
});

describe('bitpanda', () => {
  it('reconnaît le préambule et l’en-tête direct ; rejette un en-tête étranger et une ligne courte sans mention Bitpanda', () => {
    expect(bitpanda.detect(parseCsvText(CSV).header)).toBe(true);
    expect(bitpanda.detect(HEADER)).toBe(true);
    expect(bitpanda.detect(FOREIGN_HEADER)).toBe(false);
    expect(bitpanda.detect(['Un simple commentaire sans rapport'])).toBe(false);
  });

  it('franchit le préambule, traite achat, vente, dépôt (brut = net + frais), retrait, transfert interne, type et classe inconnus, timestamp illisible', () => {
    const { drafts, issues, skippedInternal } = bitpanda.convert(parseCsvText(CSV));
    expect(drafts).toHaveLength(4);
    expect(skippedInternal).toBe(1);
    expect(issues).toHaveLength(3);
    expect(issues.some((i) => i.message.includes('foobar'))).toBe(true);
    expect(issues.some((i) => i.message.includes('hors périmètre crypto'))).toBe(true);
    expect(issues.some((i) => i.message.includes('Timestamp'))).toBe(true);

    const byTxId = (id: string): (typeof drafts)[number] => {
      const d = drafts.find((x) => x.txHash === id);
      if (!d) throw new Error(`brouillon ${id} introuvable`);
      return d;
    };

    const buy = byTxId('BP1');
    expect(buy.sent).toEqual({ amount: '502', currency: 'eur' });
    expect(buy.received).toEqual({ amount: '0.01', currency: 'btc' });
    expect(buy.fee).toEqual({ amount: '2', currency: 'eur' });
    expect(buy.timeMs).toBe(Date.UTC(2026, 2, 2, 8, 14, 2));

    const sell = byTxId('BP2');
    expect(sell.sent).toEqual({ amount: '0.005', currency: 'btc' });
    expect(sell.received).toEqual({ amount: '305', currency: 'eur' });
    expect(sell.fee).toEqual({ amount: '1.5', currency: 'eur' });

    const deposit = byTxId('BP3');
    expect(deposit.sent).toBeNull();
    expect(deposit.received).toEqual({ amount: '998', currency: 'eur' });
    expect(deposit.fee).toEqual({ amount: '2', currency: 'eur' });
    expect(deposit.description).toContain('1000 EUR');

    const withdrawal = byTxId('BP4');
    expect(withdrawal.received).toBeNull();
    expect(withdrawal.sent).toEqual({ amount: '0.2', currency: 'eth' });
    expect(withdrawal.fee).toEqual({ amount: '0.001', currency: 'eth' });
  });
});

describe('importAnyCsv (bitpanda)', () => {
  it('reconnaît le format via le registre malgré le préambule', () => {
    const result = importAnyCsv(CSV, {}, 'csv:bitpanda', 'i1', USD_RATE);
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.report.format).toBe('bitpanda');
    expect(result.report.counts.skippedInternal).toBe(1);
  });
});
