/**
 * **Fichier généré — ne pas modifier à la main.**
 * `node scripts/generate-tickers.mjs 500` le réécrit entièrement.
 *
 * Couverture large de la table des prix : le top 500 CoinGecko par capitalisation, au
 * 2026-08-27. Une table de marché vieillit — cette date dit de quand
 * elle parle.
 *
 * Les symboles **ambigus** en sont volontairement absents : quand deux projets partagent un
 * symbole, aucun identifiant n'est retenu, et l'actif reste sans cotation automatique plutôt que
 * de risquer un prix faux. L'utilisateur peut toujours forcer l'identifiant depuis la fiche actif.
 * Écartés à cette génération :
 * - `dai` : dai (#23) vs dai-on-pulsechain (#252)
 * - `pc0000023` : tradable-singapore-fintech-ssl-2 (#null) vs tradable-na-neobank-sstl (#329)
 * - `safe` : safecoin (#254) vs safe (#336)
 * - `up` : up-2 (#187) vs unitas (#257)
 * - `usda` : usda-2 (#260) vs usda-3 (#302)
 * - `usdf` : falcon-finance (#62) vs astherus-usdf (#244)
 *
 * Les symboles déjà présents dans la table **curée** (`tickers.ts`) ne sont pas réémis : la table
 * curée porte des décisions humaines et reste prioritaire.
 */
import type { TickerInfo } from './tickers';

/** Entrée générée : identifiant CoinGecko seulement — CoinGecko ne connaît ni Coinbase ni Kraken. */
const G = (name: string, coingeckoId: string): TickerInfo => ({
  name,
  coingeckoId,
  coinbase: null,
});

export const GENERATED_TICKERS: Record<string, TickerInfo> = {
  '1inch': G('1INCH', '1inch'),
  '2z': G('DoubleZero', 'doublezero'),
  a7a5: G('A7A5', 'a7a5'),
  ab: G('AB', 'newton-project'),
  acrdx: G(
    'Anemoy Tokenized Apollo Diversified Credit Fund',
    'anemoy-tokenized-apollo-diversified-credit-fund',
  ),
  acred: G(
    'Apollo Diversified Credit Securitize Fund',
    'apollo-diversified-credit-securitize-fund',
  ),
  acu: G('Acurast', 'acurast'),
  adi: G('ADI', 'adi-token'),
  aero: G('Aerodrome Finance', 'aerodrome-finance'),
  aioz: G('AIOZ Network', 'aioz-network'),
  aix: G('AI XOVIA', 'ai-xovia'),
  ake: G('Akedo', 'akedo'),
  akt: G('Akash Network', 'akash-network'),
  alfw: G('Alpha Bulgaria Warrants', 'alpha-bulgaria-warrants'),
  allo: G('Allora', 'allora'),
  alt: G('AltLayer', 'altlayer'),
  ansem: G('The Black Bull', 'the-black-bull'),
  antfun: G('AntFun', 'antfun'),
  anvl: G('Anvil', 'anvil'),
  apepe: G('Ape and Pepe', 'ape-and-pepe'),
  apes: G('APES', 'apes-2-2'),
  apr: G('Capricorn', 'apriori'),
  apxusd: G('apxUSD', 'apxusd'),
  apyusd: G('apyUSD', 'apyusd'),
  ar: G('Arweave', 'arweave'),
  arc: G('AI Rig Complex', 'ai-rig-complex'),
  arkm: G('Arkham', 'arkham'),
  aster: G('Aster', 'aster-2'),
  astr: G('Astar', 'astar'),
  ath: G('Aethir', 'aethir'),
  ausd: G('AUSD', 'agora-dollar'),
  ausdt: G('Alloy Tether', 'alloy-tether'),
  avusd: G('Avant USD', 'avant-usd'),
  awe: G('AWE Network', 'stp-network'),
  axl: G('Axelar', 'axelar'),
  baby: G('Babylon', 'babylon'),
  babyclaw: G('Baby Claw', 'baby-claw'),
  babydoge: G('Baby Doge Coin', 'baby-doge-coin'),
  ban: G('Comedian', 'comedian'),
  bananas31: G('Banana For Scale', 'banana-for-scale-2'),
  bas: G('BNB Attestation Service', 'bas'),
  basedhype: G('BasedHype', 'basedhype'),
  bc: G('BCGame Coin', 'bc-token'),
  bcap: G('Blockchain Capital', 'blockchain-capital'),
  bce: G('bitcastle Token', 'bitcastle-token'),
  bdx: G('Beldex', 'beldex'),
  beam: G('Beam', 'beam-2'),
  bera: G('Berachain', 'berachain-bera'),
  bfusd: G('BFUSD', 'bfusd'),
  bgb: G('Bitget Token', 'bitget-token'),
  bgbtc: G('Bitget Wrapped BTC', 'bitget-wrapped-btc'),
  bill: G('Billions Network', 'billions-network'),
  bim: G('BIM', 'bim-2'),
  bio: G('Bio Protocol', 'bio-protocol'),
  blur: G('Blur', 'blur'),
  bnb: G('BNB', 'binancecoin'),
  bome: G('BOOK OF MEME', 'book-of-meme'),
  borg: G('SwissBorg', 'swissborg'),
  bp: G('Backpack', 'backpack'),
  br: G('Bedrock', 'bedrock-token'),
  brett: G('Brett', 'based-brett'),
  brlv: G('Crown BRLV', 'crown-brlv'),
  brsrv: G(
    'BlackRock Daily Reinvestment Stablecoin Reserve Vehicle',
    'blackrock-daily-reinvestment-stablecoin-reserve-vehicle',
  ),
  brz: G('Brazilian Digital', 'brz'),
  bspx: G('Bending Spoons xStock', 'bending-spoons-xstock'),
  bsv: G('Bitcoin SV', 'bitcoin-cash-sv'),
  btse: G('BTSE Token', 'btse-token'),
  btt: G('BitTorrent', 'bittorrent'),
  btw: G('Bitway', 'bitway'),
  buidl: G(
    'BlackRock USD Institutional Digital Liquidity Fund',
    'blackrock-usd-institutional-digital-liquidity-fund',
  ),
  cake: G('PancakeSwap', 'pancakeswap-token'),
  cap: G('Cap', 'cap-4'),
  cards: G('Collector Crypt', 'collector-crypt'),
  cash: G('CASH', 'cash-4'),
  cashcat: G('Cash Cat', 'cash-cat'),
  cc: G('Canton', 'canton-network'),
  celo: G('Celo', 'celo'),
  cfg: G('Centrifuge', 'centrifuge-2'),
  cfx: G('Conflux', 'conflux-token'),
  cgusd: G('Cygnus Finance Global USD', 'cygnus-finance-global-usd'),
  cheems: G('Cheems Token', 'cheems-token'),
  chfau: G('AllUnity CHF', 'allunity-chf'),
  chip: G('USD.AI', 'chip-2'),
  ckb: G('Nervos Network', 'nervos-network'),
  coai: G('ChainOpera AI', 'chainopera-ai'),
  coco: G('coco', 'coco-2'),
  comp: G('Compound', 'compound-governance-token'),
  cow: G('CoW Protocol', 'cow-protocol'),
  crclb: G('Circle Internet Group (bStocks Tokenized Stock)', 'circle-internet-group-bstock'),
  crclon: G(
    'Circle Internet Group (Ondo Tokenized Stock)',
    'circle-internet-group-ondo-tokenized-stock',
  ),
  crclx: G('Circle xStock', 'circle-xstock'),
  cro: G('Cronos', 'crypto-com-chain'),
  crvusd: G('crvUSD', 'crvusd'),
  cspr: G('Casper Network', 'casper-network'),
  ctc: G('Creditcoin', 'creditcoin-2'),
  cusd: G('Cap USD', 'cap-usd'),
  cvx: G('Convex Finance', 'convex-finance'),
  cys: G('Cysic', 'cysic'),
  dash: G('Dash', 'dash'),
  data: G('Data Network', 'story-2'),
  dbr: G('deBridge', 'debridge'),
  dcr: G('Decred', 'decred'),
  dexe: G('DeXe', 'dexe'),
  dgai: G('DGrid AI', 'dgrid-ai'),
  dgb: G('DigiByte', 'digibyte'),
  diem: G('Diem', 'diem'),
  dog: G('Dog (Bitcoin)', 'dog-go-to-the-moon-rune'),
  dola: G('DOLA', 'dola-usd'),
  dos: G('DAPPOS', 'dappos'),
  drv: G('Derive', 'derive'),
  dusd: G('StandX DUSD', 'standx-dusd'),
  edge: G('edgeX', 'edgex'),
  eigen: G('EigenCloud (prev. EigenLayer)', 'eigenlayer'),
  elf: G('aelf', 'aelf'),
  elg: G('Escoin', 'escoin-token'),
  ena: G('Ethena', 'ethena'),
  esp: G('Espresso', 'espresso'),
  etc: G('Ethereum Classic', 'ethereum-classic'),
  ethfi: G('Ether.fi', 'ether-fi'),
  eursafo: G('Spiko Amundi Overnight Swap Fund (EUR)', 'spiko-amundi-overnight-swap-fund-eur'),
  eutbl: G('Spiko EU T-Bills Money Market Fund', 'eutbl'),
  exod: G('EXOD', 'exod'),
  fartcoin: G('Fartcoin', 'fartcoin'),
  fdit: G('Fidelity Digital Interest Token', 'fidelity-digital-interest-token'),
  fdusd: G('First Digital USD', 'first-digital-usd'),
  feusd: G('Felix feUSD', 'felix-feusd'),
  ff: G('Falcon Finance', 'falcon-finance-ff'),
  fidd: G('Fidelity Digital Dollar', 'fidelity-digital-dollar'),
  fil: G('Filecoin', 'filecoin'),
  fiusd: G('Sygnum FIUSD Liquidity Fund', 'sygnum-fiusd-liquidity-fund'),
  flow: G('Flow', 'flow'),
  flr: G('Flare', 'flare-networks'),
  fluid: G('Fluid', 'instadapp'),
  fonq: G('FONQ', 'fonq'),
  form: G('Four', 'four'),
  frax: G('Legacy Frax Dollar', 'frax'),
  frxusd: G('Frax USD', 'frax-usd'),
  ft: G('Flying Tulip', 'flying-tulip'),
  fun: G('FUNToken', 'funfair'),
  fxsave: G('f(x) USD Saving', 'fx-usd-saving'),
  fxusd: G('f(x) Protocol fxUSD', 'f-x-protocol-fxusd'),
  gala: G('GALA', 'gala'),
  gas: G('Gas', 'gas'),
  gcoin: G('Playnance', 'playnance'),
  gekko: G('GEKKO', 'gekko'),
  genius: G('Genius', 'genius-3'),
  geod: G('Geodnet', 'geodnet'),
  ggbr: G('Goldfish Gold', 'goldfish-gold'),
  gho: G('GHO', 'gho'),
  glm: G('Golem', 'golem'),
  gomining: G('GoMining Token', 'gmt-token'),
  gps: G('GoPlus Security', 'goplus-security'),
  gram: G('Gram (prev. Toncoin)', 'the-open-network'),
  grass: G('Grass', 'grass'),
  grt: G('The Graph', 'the-graph'),
  grx: G('GRX Chain', 'grx-chain'),
  gt: G('Gate', 'gatechain-token'),
  gusd: G('GUSD', 'gusd'),
  gwei: G('ETHGas', 'ethgas-2'),
  hash: G('Provenance Blockchain', 'hash-2'),
  hbar: G('Hedera', 'hedera-hashgraph'),
  hdx: G('Hydration', 'hydradx'),
  holo: G('Holoworld', 'holoworld'),
  hot: G('Holo', 'holotoken'),
  htx: G('HTX DAO', 'htx-dao'),
  icp: G('Internet Computer', 'internet-computer'),
  imx: G('Immutable', 'immutable-x'),
  io: G('io.net', 'io'),
  iota: G('IOTA', 'iota'),
  iusd: G('InfiniFi USD', 'infinifi-usd'),
  ivvon: G(
    'iShares Core S&P 500 ETF (Ondo Tokenized ETF)',
    'ishares-core-s-p-500-etf-ondo-tokenized-etf',
  ),
  jaaa: G('Janus Henderson Anemoy AAA CLO Fund', 'janus-henderson-anemoy-aaa-clo-fund'),
  jasmy: G('JasmyCoin', 'jasmycoin'),
  jellyjelly: G('Jelly-My-Jelly', 'jelly-my-jelly'),
  jpyc: G('JPY Coin', 'jpycoin'),
  jpysc: G('JPYSC', 'jpysc'),
  jst: G('JUST', 'just'),
  jto: G('Jito', 'jito-governance-token'),
  jtrsy: G('Janus Henderson Anemoy Treasury Fund', 'janus-henderson-anemoy-treasury-fund'),
  jup: G('Jupiter', 'jupiter-exchange-solana'),
  jupusd: G('JupUSD', 'jupusd'),
  kag: G('Kinesis Silver', 'kinesis-silver'),
  kaia: G('Kaia', 'kaia'),
  kaito: G('KAITO', 'kaito'),
  kas: G('Kaspa', 'kaspa'),
  kau: G('Kinesis Gold', 'kinesis-gold'),
  kava: G('Kava', 'kava'),
  kcs: G('KuCoin', 'kucoin-shares'),
  kite: G('Kite', 'kite-2'),
  kmno: G('Kamino', 'kamino'),
  kntq: G('Kinetiq', 'kinetiq'),
  koge: G('KOGE', 'bnb48-club-token'),
  lab: G('LAB', 'lab'),
  leo: G('LEO Token', 'leo-token'),
  linea: G('Linea', 'linea'),
  lion: G('Loaded Lions', 'loaded-lions'),
  lisusd: G('Lista USD', 'helio-protocol-hay'),
  lit: G('Lighter', 'lighter'),
  lpt: G('Livepeer', 'livepeer'),
  lunc: G('Terra Luna Classic', 'terra-luna'),
  magma: G('Magma Finance', 'magma-finance'),
  melania: G('Melania Meme', 'melania-meme'),
  meme: G('MEMETOON', 'memetoon'),
  met: G('Meteora', 'meteora'),
  meta: G('MetaDAO', 'meta-2-2'),
  metal: G('Metal Blockchain', 'metal-blockchain'),
  mglobal: G('Midas Fasanara Global', 'midas-fasanara-global'),
  mhorse: G('MEME HORSE', 'meme-horse'),
  mina: G('Mina Protocol', 'mina-protocol'),
  mnt: G('Mantle', 'mantle'),
  mog: G('Mog Coin', 'mog-coin'),
  mon: G('Monad', 'monad'),
  morpho: G('Morpho', 'morpho'),
  mstrx: G('MicroStrategy xStock', 'microstrategy-xstock'),
  mtbill: G('Midas mTBILL', 'midas-mtbill'),
  mx: G('MX', 'mx-token'),
  neo: G('NEO', 'neo'),
  nex: G('Nexus', 'nexus-4'),
  nexo: G('NEXO', 'nexo'),
  nft: G('AINFT', 'apenft'),
  night: G('Midnight', 'midnight-3'),
  nila: G('MindWaveDAO', 'mindwavedao'),
  nmr: G('Numeraire', 'numeraire'),
  nopal: G('Nest BlackOpal LiquidStone II Vault', 'nest-blackopal-liquidstone-ii-vault'),
  npc: G('Non-Playable Coin', 'non-playable-coin'),
  nusd: G('Neutrl USD', 'nusd-2'),
  nxm: G('Nexus Mutual', 'nxm'),
  nxpc: G('Nexpace', 'nexpace'),
  ohm: G('Olympus', 'olympus'),
  okb: G('OKB', 'okb'),
  omi: G('ECOMI', 'ecomi'),
  one: G('ONEchain', 'cross-2'),
  ong: G('Ontology Gas', 'ong'),
  ont: G('Ontology', 'ontology'),
  onyc: G('OnRe Tokenized Reinsurance', 'onyc'),
  orca: G('Orca', 'orca'),
  ordi: G('ORDI', 'ordinals'),
  ousg: G('Ondo Short-Term U.S. Government Bond Fund', 'ousg'),
  oza: G('Ozapay', 'ozapay'),
  ozo: G('Ozone Chain', 'ozone-chain'),
  pc: G('Pentagon Chain', 'pentagon-chain'),
  pc0000015: G(
    'Tradable NA Third Party Online Merchant SSTN',
    'tradable-na-third-party-online-merchant-sstn',
  ),
  pc0000019: G('Tradable North America PoS Lender SSTN', 'tradable-north-america-pos-lender-sstn'),
  pc0000027: G('Tradable LatAm BNPL SSTN', 'tradable-latam-bnpl-sstn'),
  pc0000031: G(
    'Tradable NA Rent Financing Platform SSTN',
    'tradable-na-rent-financing-platform-sstn',
  ),
  pc0000033: G(
    'Tradable APAC Diversified Finance Provider SSTN',
    'tradable-apac-diversified-finance-provider-sstn',
  ),
  pc0000049: G('Tradable Eu/LatAm PoS Financing SSTL', 'tradable-eu-latam-pos-financing-sstl'),
  pc0000077: G('Tradable Singapore Fintech SSL', 'tradable-singapore-fintech-ssl'),
  pc0000081: G('Tradable NA Legal Receivables SSL', 'tradable-na-legal-receivables-ssl'),
  pc0000085: G(
    'Tradable LatAm Middle-Market Lender SSTL',
    'tradable-latam-middle-market-lender-sstl',
  ),
  pc0000097: G('Tradable LatAm Fintech SSTN', 'tradable-latam-fintech-sstn'),
  pc0000101: G(
    'Tradable NA Post-Settlement Legal Financing Receivables',
    'na-post-settlement-legal-financing-receivables',
  ),
  pc0016245: G('NA Capital-as-a-Service SSTN', 'na-capital-as-a-service-sstn'),
  peaq: G('peaq', 'peaq-2'),
  pendle: G('Pendle', 'pendle'),
  pengu: G('Pudgy Penguins', 'pudgy-penguins'),
  pgold: G('Pleasing Gold', 'pleasing-gold'),
  pi: G('Pi Network', 'pi-network'),
  pieverse: G('Pieverse', 'pieverse'),
  plume: G('Plume', 'plume'),
  pmusd: G('Precious Metals USD', 'precious-metals-usd'),
  pnut: G('Peanut the Squirrel', 'peanut-the-squirrel'),
  polyx: G('Polymesh', 'polymesh'),
  pons: G('Pons', 'pons'),
  popcat: G('Popcat', 'popcat'),
  prize: G('Prize Protocol', 'prize-protocol'),
  prl: G('Pearl', 'pearl-2'),
  prom: G('Prom', 'prometeus'),
  pros: G('Pharos', 'pharos-network'),
  pump: G('Pump.fun', 'pump-fun'),
  purr: G('Purr', 'purr-2'),
  pyth: G('Pyth Network', 'pyth-network'),
  pyusd: G('PayPal USD', 'paypal-usd'),
  qnt: G('Quant', 'quant-network'),
  qrl: G('Quantum Resistant Ledger', 'quantum-resistant-ledger'),
  qtum: G('Qtum', 'qtum'),
  qubic: G('Qubic', 'qubic-network'),
  rail: G('Railgun', 'railgun'),
  rain: G('Rain', 'rain'),
  rave: G('RaveDAO', 'ravedao'),
  ray: G('Raydium', 'raydium'),
  re: G('RE', 're'),
  real: G('RealLink', 'reallink'),
  red: G('RedStone', 'redstone-oracles'),
  rekt: G('Rekt', 'rekt-4'),
  req: G('Request', 'request-network'),
  reur: G('Royal Euro', 'royal-euro'),
  reusd: G('Re Protocol reUSD', 're-protocol-reusd'),
  rif: G('Rootstock Infrastructure Framework', 'rif-token'),
  rlb: G('Rollbit Coin', 'rollbit-coin'),
  rlusd: G('Ripple USD', 'ripple-usd'),
  rose: G('Oasis', 'oasis-network'),
  rsr: G('Reserve Rights', 'reserve-rights-token'),
  rune: G('THORChain', 'thorchain'),
  rvn: G('Ravencoin', 'ravencoin'),
  safo: G('Spiko Amundi Overnight Swap Fund', 'safo'),
  sei: G('Sei', 'sei-network'),
  sent: G('Sentient', 'sentient'),
  sfp: G('SafePal', 'safepal'),
  shfl: G('Shuffle', 'shuffle-2'),
  short: G('Bermuda Shorts', 'bermuda-shorts'),
  shx: G('Stronghold', 'stronghold-token'),
  skr: G('Seeker', 'seeker'),
  skyai: G('SkyAI', 'skyai'),
  sn120: G('affine', 'affine'),
  sn4: G('Targon', 'targon'),
  sn44: G('Score', 'score'),
  sn51: G('lium', 'celium'),
  sn64: G('Chutes', 'chutes'),
  sofid: G('SoFiUSD', 'sofiusd'),
  soon: G('SOON', 'soon-2'),
  soso: G('SoSoValue', 'sosovalue'),
  spcxb: G('SpaceX (bStocks Tokenized Stock)', 'spacex-bstocks-tokenized-stock'),
  spk: G('Spark', 'spark-2'),
  spx: G('SPX6900', 'spx6900'),
  spyx: G('SP500 xStock', 'sp500-xstock'),
  stable: G('​​Stable', 'stable-2'),
  stac: G('Securitize Tokenized AAA CLO Fund', 'securitize-tokenized-aaa-clo-fund'),
  stau: G('STAU', 'stau'),
  strcx: G('Strategy PP Variable xStock', 'strategy-pp-variable-xstock'),
  strk: G('Starknet', 'starknet'),
  stx: G('Stacks', 'blockstack'),
  sun: G('Sun Token', 'sun-token'),
  super: G('SuperVerse', 'superfarm'),
  swop: G('Swop', 'swop-2'),
  syrup: G('Maple Finance', 'syrup'),
  tag: G('TAGGER', 'tagger'),
  tel: G('Telcoin', 'telcoin'),
  temple: G('TempleDAO', 'temple'),
  tfuel: G('Theta Fuel', 'theta-fuel'),
  thbill: G('Theo Short Duration US Treasury Fund', 'theo-short-duration-us-treasury-fund'),
  tibbir: G('Ribbita by Virtuals', 'ribbita-by-virtuals'),
  toshi: G('Toshi', 'toshi'),
  trac: G('OriginTrail', 'origintrail'),
  trb: G('Tellor Tributes', 'tellor'),
  troll: G('TROLL', 'troll-2'),
  trump: G('Official Trump', 'official-trump'),
  trusd: G('Tori trUSD', 'tori-trusd'),
  tslax: G('Tesla xStock', 'tesla-xstock'),
  turbo: G('Turbo', 'turbo'),
  tusd: G('TrueUSD', 'true-usd'),
  twt: G('Trust Wallet', 'trust-wallet-token'),
  uai: G('UnifAI Network', 'unifai-network'),
  ub: G('Unibase', 'unibase'),
  ultima: G('Ultima', 'ultima'),
  unt: G('UnityWallet Token', 'unitywallet-token'),
  us: G('Talus', 'talus'),
  usat: G('USAT', 'usa'),
  usd0: G('Usual USD', 'usual-usd'),
  usd1: G('USD1', 'usd1-wlfi'),
  usdai: G('USDai', 'usdai'),
  usdat: G('Saturn Dollar', 'saturn-dollar'),
  usdd: G('USDD', 'usdd'),
  usde: G('Ethena USDe', 'ethena-usde'),
  usdg: G('Global Dollar', 'global-dollar'),
  usdgo: G('USDGO', 'usdgo'),
  usdkg: G('USDKG', 'usdkg'),
  usdon: G('Ondo U.S. Dollar Token', 'ondo-u-s-dollar-token'),
  usdsui: G('USDsui', 'usdsui'),
  usdtb: G('USDtb', 'usdtb'),
  usdu: G('USDu', 'usdu'),
  usdy: G('Ondo US Dollar Yield', 'ondo-us-dollar-yield'),
  useless: G('Useless Coin', 'useless-3'),
  ustb: G(
    'Invesco Short Duration US Government Securities Fund',
    'superstate-short-duration-us-government-securities-fund-ustb',
  ),
  ustbl: G('Spiko US T-Bills Money Market Fund', 'spiko-us-t-bills-money-market-fund'),
  usx: G('USX', 'usx'),
  usyc: G('Circle USYC', 'hashnote-usyc'),
  uusd: G('Unity USD', 'unity-usd'),
  vbill: G('VanEck Treasury Fund', 'vaneck-treasury-fund'),
  velo: G('Velo', 'velo'),
  velvet: G('Velvet', 'velvet'),
  virtual: G('Virtuals Protocol', 'virtual-protocol'),
  vsn: G('Vision', 'vision-3'),
  vvv: G('Venice Token', 'venice-token'),
  wal: G('Walrus', 'walrus-2'),
  wbt: G('WhiteBIT Coin', 'whitebit'),
  wemix: G('WEMIX', 'wemix-token'),
  wkc: G('Wiki Cat', 'wiki-cat'),
  wld: G('Worldcoin', 'worldcoin-wld'),
  wlfi: G('World Liberty Financial', 'world-liberty-financial'),
  wm: G('WrappedM by M0', 'wrappedm-by-m0'),
  would: G('would', 'would'),
  xaum: G('Matrixdock Gold', 'matrixdock-gold'),
  xaut: G('Tether Gold', 'tether-gold'),
  xcn: G('Onyxcoin', 'chain-2'),
  xdc: G('XDC Network', 'xdce-crowd-sale'),
  xec: G('eCash', 'ecash'),
  xmr: G('Monero', 'monero'),
  xno: G('Nano', 'nano'),
  xp: G('Xphere', 'xphere'),
  xpin: G('XPIN Network', 'xpin-network'),
  xpl: G('Plasma', 'plasma'),
  xpr: G('XPR Network', 'proton'),
  xusd: G('StraitsX XUSD', 'straitsx-xusd'),
  xvs: G('Venus', 'venus'),
  xyo: G('XYO Network', 'xyo-network'),
  ylds: G('YLDS', 'ylds'),
  yzy: G('YZY', 'yzy'),
  zama: G('Zama', 'zama'),
  zano: G('Zano', 'zano'),
  zbcn: G('Zebec Network', 'zebec-network'),
  zec: G('Zcash', 'zcash'),
  zen: G('Horizen', 'zencash'),
  zeta: G('ZetaChain', 'zetachain'),
  zig: G('ZIGChain', 'zignaly'),
  zil: G('Zilliqa', 'zilliqa'),
  zk: G('ZKsync', 'zksync'),
  zro: G('LayerZero', 'layerzero'),
  zrx: G('0x Protocol', '0x'),
};

/** Symboles écartés pour ambiguïté, avec leurs candidats : lus par le test de non-régression. */
export const AMBIGUOUS_SYMBOLS: readonly string[] = [
  'dai',
  'pc0000023',
  'safe',
  'up',
  'usda',
  'usdf',
];
