// @generated par `node scripts/generate-calendar.ts` — NE PAS MODIFIER À LA MAIN.
//
// Les dates du BLS viennent de `bls-schedule.ts`, tenu à la main ; celles du FOMC et du BEA
// sont relues automatiquement. Voir `types.ts` pour ce que chaque champ engage.

import type { Calendar } from './types';

export const CALENDAR: Calendar = {
  generatedAt: '2026-09-04T11:17:50Z',
  coversFrom: '2026-06-05',
  coversTo: '2028-12-07',
  completeTo: '2026-12-15',
  sources: [
    { source: 'fomc', checkedOn: '2026-09-04', count: 13, coversTo: '2027-12-08', upkeep: 'auto' },
    { source: 'bea', checkedOn: '2026-09-04', count: 14, coversTo: '2026-12-23', upkeep: 'auto' },
    { source: 'bls', checkedOn: '2026-09-01', count: 27, coversTo: '2026-12-15', upkeep: 'manual' },
    { source: 'ecb', checkedOn: '2026-09-04', count: 19, coversTo: '2028-12-07', upkeep: 'auto' },
    {
      source: 'eurostat',
      checkedOn: '2026-09-04',
      count: 9,
      coversTo: '2027-01-19',
      upkeep: 'auto',
    },
  ],
  events: [
    {
      id: 'bls-employment-2026-06-05',
      kind: 'employment',
      at: '2026-06-05T12:30:00Z',
      precision: 'exact',
      title: 'Emploi américain (rapport mensuel)',
      detail: 'Données de mai 2026',
      tier: 'major',
      source: 'bls',
      url: 'https://www.bls.gov/schedule/news_release/empsit.htm',
    },
    {
      id: 'bls-cpi-2026-06-10',
      kind: 'cpi',
      at: '2026-06-10T12:30:00Z',
      precision: 'exact',
      title: 'Inflation américaine (CPI)',
      detail: 'Données de mai 2026',
      tier: 'major',
      source: 'bls',
      url: 'https://www.bls.gov/schedule/news_release/cpi.htm',
    },
    {
      id: 'bls-ppi-2026-06-11',
      kind: 'ppi',
      at: '2026-06-11T12:30:00Z',
      precision: 'exact',
      title: 'Prix à la production (PPI)',
      detail: 'Données de mai 2026',
      tier: 'secondary',
      source: 'bls',
      url: 'https://www.bls.gov/schedule/news_release/ppi.htm',
    },
    {
      id: 'fomc-decision-2026-06-17',
      kind: 'fomc-decision',
      at: '2026-06-17T18:00:00Z',
      precision: 'exact',
      title: 'Décision de la Fed (FOMC)',
      detail: 'Communiqué, conférence de presse et projections économiques',
      tier: 'major',
      source: 'fomc',
      url: 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
    },
    {
      id: 'bea-gdp-2026-06-25',
      kind: 'gdp',
      at: '2026-06-25T12:30:00Z',
      precision: 'exact',
      title: 'PIB américain',
      tier: 'major',
      source: 'bea',
      url: 'https://www.bea.gov/data/gdp/gross-domestic-product',
    },
    {
      id: 'bea-pce-2026-06-25',
      kind: 'pce',
      at: '2026-06-25T12:30:00Z',
      precision: 'exact',
      title: 'Inflation PCE et revenus des ménages',
      detail: 'La mesure d’inflation que la Fed regarde en priorité',
      tier: 'major',
      source: 'bea',
      url: 'https://www.bea.gov/data/income-saving/personal-income',
    },
    {
      id: 'bls-jolts-2026-06-30',
      kind: 'jolts',
      at: '2026-06-30T14:00:00Z',
      precision: 'exact',
      title: 'Postes vacants (JOLTS)',
      detail: 'Données de mai 2026',
      tier: 'secondary',
      source: 'bls',
      url: 'https://www.bls.gov/schedule/news_release/jolts.htm',
    },
    {
      id: 'bls-employment-2026-07-02',
      kind: 'employment',
      at: '2026-07-02T12:30:00Z',
      precision: 'exact',
      title: 'Emploi américain (rapport mensuel)',
      detail: 'Données de juin 2026',
      tier: 'major',
      source: 'bls',
      url: 'https://www.bls.gov/schedule/news_release/empsit.htm',
    },
    {
      id: 'bls-cpi-2026-07-14',
      kind: 'cpi',
      at: '2026-07-14T12:30:00Z',
      precision: 'exact',
      title: 'Inflation américaine (CPI)',
      detail: 'Données de juin 2026',
      tier: 'major',
      source: 'bls',
      url: 'https://www.bls.gov/schedule/news_release/cpi.htm',
    },
    {
      id: 'bls-ppi-2026-07-15',
      kind: 'ppi',
      at: '2026-07-15T12:30:00Z',
      precision: 'exact',
      title: 'Prix à la production (PPI)',
      detail: 'Données de juin 2026',
      tier: 'secondary',
      source: 'bls',
      url: 'https://www.bls.gov/schedule/news_release/ppi.htm',
    },
    {
      id: 'fomc-decision-2026-07-29',
      kind: 'fomc-decision',
      at: '2026-07-29T18:00:00Z',
      precision: 'exact',
      title: 'Décision de la Fed (FOMC)',
      detail: 'Communiqué et conférence de presse',
      tier: 'major',
      source: 'fomc',
      url: 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
    },
    {
      id: 'bea-gdp-2026-07-30',
      kind: 'gdp',
      at: '2026-07-30T12:30:00Z',
      precision: 'exact',
      title: 'PIB américain',
      tier: 'major',
      source: 'bea',
      url: 'https://www.bea.gov/data/gdp/gross-domestic-product',
    },
    {
      id: 'bea-pce-2026-07-30',
      kind: 'pce',
      at: '2026-07-30T12:30:00Z',
      precision: 'exact',
      title: 'Inflation PCE et revenus des ménages',
      detail: 'La mesure d’inflation que la Fed regarde en priorité',
      tier: 'major',
      source: 'bea',
      url: 'https://www.bea.gov/data/income-saving/personal-income',
    },
    {
      id: 'bls-jolts-2026-08-04',
      kind: 'jolts',
      at: '2026-08-04T14:00:00Z',
      precision: 'exact',
      title: 'Postes vacants (JOLTS)',
      detail: 'Données de juin 2026',
      tier: 'secondary',
      source: 'bls',
      url: 'https://www.bls.gov/schedule/news_release/jolts.htm',
    },
    {
      id: 'bls-employment-2026-08-07',
      kind: 'employment',
      at: '2026-08-07T12:30:00Z',
      precision: 'exact',
      title: 'Emploi américain (rapport mensuel)',
      detail: 'Données de juillet 2026',
      tier: 'major',
      source: 'bls',
      url: 'https://www.bls.gov/schedule/news_release/empsit.htm',
    },
    {
      id: 'bls-cpi-2026-08-12',
      kind: 'cpi',
      at: '2026-08-12T12:30:00Z',
      precision: 'exact',
      title: 'Inflation américaine (CPI)',
      detail: 'Données de juillet 2026',
      tier: 'major',
      source: 'bls',
      url: 'https://www.bls.gov/schedule/news_release/cpi.htm',
    },
    {
      id: 'bls-ppi-2026-08-13',
      kind: 'ppi',
      at: '2026-08-13T12:30:00Z',
      precision: 'exact',
      title: 'Prix à la production (PPI)',
      detail: 'Données de juillet 2026',
      tier: 'secondary',
      source: 'bls',
      url: 'https://www.bls.gov/schedule/news_release/ppi.htm',
    },
    {
      id: 'bea-gdp-2026-08-26',
      kind: 'gdp',
      at: '2026-08-26T12:30:00Z',
      precision: 'exact',
      title: 'PIB américain',
      tier: 'major',
      source: 'bea',
      url: 'https://www.bea.gov/data/gdp/gross-domestic-product',
    },
    {
      id: 'bea-pce-2026-08-26',
      kind: 'pce',
      at: '2026-08-26T12:30:00Z',
      precision: 'exact',
      title: 'Inflation PCE et revenus des ménages',
      detail: 'La mesure d’inflation que la Fed regarde en priorité',
      tier: 'major',
      source: 'bea',
      url: 'https://www.bea.gov/data/income-saving/personal-income',
    },
    {
      id: 'bls-jolts-2026-09-01',
      kind: 'jolts',
      at: '2026-09-01T14:00:00Z',
      precision: 'exact',
      title: 'Postes vacants (JOLTS)',
      detail: 'Données de juillet 2026',
      tier: 'secondary',
      source: 'bls',
      url: 'https://www.bls.gov/schedule/news_release/jolts.htm',
    },
    {
      id: 'bls-employment-2026-09-04',
      kind: 'employment',
      at: '2026-09-04T12:30:00Z',
      precision: 'exact',
      title: 'Emploi américain (rapport mensuel)',
      detail: 'Données d’août 2026',
      tier: 'major',
      source: 'bls',
      url: 'https://www.bls.gov/schedule/news_release/empsit.htm',
    },
    {
      id: 'ecb-decision-2026-09-10',
      kind: 'ecb-decision',
      at: '2026-09-10T12:15:00Z',
      precision: 'day',
      title: 'Décision de la BCE (Conseil des gouverneurs)',
      detail: 'Communiqué puis conférence de presse',
      tier: 'major',
      source: 'ecb',
      url: 'https://www.ecb.europa.eu/press/calendars/mgcgc/html/index.en.html',
    },
    {
      id: 'bls-ppi-2026-09-10',
      kind: 'ppi',
      at: '2026-09-10T12:30:00Z',
      precision: 'exact',
      title: 'Prix à la production (PPI)',
      detail: 'Données d’août 2026',
      tier: 'secondary',
      source: 'bls',
      url: 'https://www.bls.gov/schedule/news_release/ppi.htm',
    },
    {
      id: 'bls-cpi-2026-09-11',
      kind: 'cpi',
      at: '2026-09-11T12:30:00Z',
      precision: 'exact',
      title: 'Inflation américaine (CPI)',
      detail: 'Données d’août 2026',
      tier: 'major',
      source: 'bls',
      url: 'https://www.bls.gov/schedule/news_release/cpi.htm',
    },
    {
      id: 'fomc-decision-2026-09-16',
      kind: 'fomc-decision',
      at: '2026-09-16T18:00:00Z',
      precision: 'exact',
      title: 'Décision de la Fed (FOMC)',
      detail: 'Communiqué, conférence de presse et projections économiques',
      tier: 'major',
      source: 'fomc',
      url: 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
    },
    {
      id: 'eurostat-hicp-final-2026-09-17',
      kind: 'hicp',
      at: '2026-09-17T10:00:00Z',
      precision: 'exact',
      title: 'Inflation zone euro (définitif)',
      detail: 'IPCH, chiffre révisé',
      tier: 'secondary',
      source: 'eurostat',
      url: 'https://www.ecb.europa.eu/press/calendars/statscal/ges/html/sthicp.en.html',
    },
    {
      id: 'bls-jolts-2026-09-29',
      kind: 'jolts',
      at: '2026-09-29T14:00:00Z',
      precision: 'exact',
      title: 'Postes vacants (JOLTS)',
      detail: 'Données d’août 2026',
      tier: 'secondary',
      source: 'bls',
      url: 'https://www.bls.gov/schedule/news_release/jolts.htm',
    },
    {
      id: 'bea-gdp-2026-09-30',
      kind: 'gdp',
      at: '2026-09-30T12:30:00Z',
      precision: 'exact',
      title: 'PIB américain',
      tier: 'major',
      source: 'bea',
      url: 'https://www.bea.gov/data/gdp/gross-domestic-product',
    },
    {
      id: 'bea-pce-2026-09-30',
      kind: 'pce',
      at: '2026-09-30T12:30:00Z',
      precision: 'exact',
      title: 'Inflation PCE et revenus des ménages',
      detail: 'La mesure d’inflation que la Fed regarde en priorité',
      tier: 'major',
      source: 'bea',
      url: 'https://www.bea.gov/data/income-saving/personal-income',
    },
    {
      id: 'bls-employment-2026-10-02',
      kind: 'employment',
      at: '2026-10-02T12:30:00Z',
      precision: 'exact',
      title: 'Emploi américain (rapport mensuel)',
      detail: 'Données de septembre 2026',
      tier: 'major',
      source: 'bls',
      url: 'https://www.bls.gov/schedule/news_release/empsit.htm',
    },
    {
      id: 'eurostat-hicp-flash-2026-10-02',
      kind: 'hicp',
      at: '2026-10-02T13:00:00Z',
      precision: 'exact',
      title: 'Inflation zone euro (estimation rapide)',
      detail: 'IPCH, première estimation',
      tier: 'major',
      source: 'eurostat',
      url: 'https://www.ecb.europa.eu/press/calendars/statscal/ges/html/sthicp.en.html',
    },
    {
      id: 'bls-cpi-2026-10-14',
      kind: 'cpi',
      at: '2026-10-14T12:30:00Z',
      precision: 'exact',
      title: 'Inflation américaine (CPI)',
      detail: 'Données de septembre 2026',
      tier: 'major',
      source: 'bls',
      url: 'https://www.bls.gov/schedule/news_release/cpi.htm',
    },
    {
      id: 'bls-ppi-2026-10-15',
      kind: 'ppi',
      at: '2026-10-15T12:30:00Z',
      precision: 'exact',
      title: 'Prix à la production (PPI)',
      detail: 'Données de septembre 2026',
      tier: 'secondary',
      source: 'bls',
      url: 'https://www.bls.gov/schedule/news_release/ppi.htm',
    },
    {
      id: 'eurostat-hicp-final-2026-10-16',
      kind: 'hicp',
      at: '2026-10-16T10:00:00Z',
      precision: 'exact',
      title: 'Inflation zone euro (définitif)',
      detail: 'IPCH, chiffre révisé',
      tier: 'secondary',
      source: 'eurostat',
      url: 'https://www.ecb.europa.eu/press/calendars/statscal/ges/html/sthicp.en.html',
    },
    {
      id: 'fomc-decision-2026-10-28',
      kind: 'fomc-decision',
      at: '2026-10-28T18:00:00Z',
      precision: 'exact',
      title: 'Décision de la Fed (FOMC)',
      detail: 'Communiqué et conférence de presse',
      tier: 'major',
      source: 'fomc',
      url: 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
    },
    {
      id: 'bea-gdp-2026-10-29',
      kind: 'gdp',
      at: '2026-10-29T12:30:00Z',
      precision: 'exact',
      title: 'PIB américain',
      tier: 'major',
      source: 'bea',
      url: 'https://www.bea.gov/data/gdp/gross-domestic-product',
    },
    {
      id: 'bea-pce-2026-10-29',
      kind: 'pce',
      at: '2026-10-29T12:30:00Z',
      precision: 'exact',
      title: 'Inflation PCE et revenus des ménages',
      detail: 'La mesure d’inflation que la Fed regarde en priorité',
      tier: 'major',
      source: 'bea',
      url: 'https://www.bea.gov/data/income-saving/personal-income',
    },
    {
      id: 'ecb-decision-2026-10-29',
      kind: 'ecb-decision',
      at: '2026-10-29T13:15:00Z',
      precision: 'day',
      title: 'Décision de la BCE (Conseil des gouverneurs)',
      detail: 'Communiqué puis conférence de presse',
      tier: 'major',
      source: 'ecb',
      url: 'https://www.ecb.europa.eu/press/calendars/mgcgc/html/index.en.html',
    },
    {
      id: 'bls-jolts-2026-11-03',
      kind: 'jolts',
      at: '2026-11-03T15:00:00Z',
      precision: 'exact',
      title: 'Postes vacants (JOLTS)',
      detail: 'Données de septembre 2026',
      tier: 'secondary',
      source: 'bls',
      url: 'https://www.bls.gov/schedule/news_release/jolts.htm',
    },
    {
      id: 'eurostat-hicp-flash-2026-11-04',
      kind: 'hicp',
      at: '2026-11-04T14:00:00Z',
      precision: 'exact',
      title: 'Inflation zone euro (estimation rapide)',
      detail: 'IPCH, première estimation',
      tier: 'major',
      source: 'eurostat',
      url: 'https://www.ecb.europa.eu/press/calendars/statscal/ges/html/sthicp.en.html',
    },
    {
      id: 'bls-employment-2026-11-06',
      kind: 'employment',
      at: '2026-11-06T13:30:00Z',
      precision: 'exact',
      title: 'Emploi américain (rapport mensuel)',
      detail: 'Données d’octobre 2026',
      tier: 'major',
      source: 'bls',
      url: 'https://www.bls.gov/schedule/news_release/empsit.htm',
    },
    {
      id: 'bls-cpi-2026-11-10',
      kind: 'cpi',
      at: '2026-11-10T13:30:00Z',
      precision: 'exact',
      title: 'Inflation américaine (CPI)',
      detail: 'Données d’octobre 2026',
      tier: 'major',
      source: 'bls',
      url: 'https://www.bls.gov/schedule/news_release/cpi.htm',
    },
    {
      id: 'bls-ppi-2026-11-13',
      kind: 'ppi',
      at: '2026-11-13T13:30:00Z',
      precision: 'exact',
      title: 'Prix à la production (PPI)',
      detail: 'Données d’octobre 2026',
      tier: 'secondary',
      source: 'bls',
      url: 'https://www.bls.gov/schedule/news_release/ppi.htm',
    },
    {
      id: 'eurostat-hicp-final-2026-11-18',
      kind: 'hicp',
      at: '2026-11-18T11:00:00Z',
      precision: 'exact',
      title: 'Inflation zone euro (définitif)',
      detail: 'IPCH, chiffre révisé',
      tier: 'secondary',
      source: 'eurostat',
      url: 'https://www.ecb.europa.eu/press/calendars/statscal/ges/html/sthicp.en.html',
    },
    {
      id: 'bea-gdp-2026-11-25',
      kind: 'gdp',
      at: '2026-11-25T13:30:00Z',
      precision: 'exact',
      title: 'PIB américain',
      tier: 'major',
      source: 'bea',
      url: 'https://www.bea.gov/data/gdp/gross-domestic-product',
    },
    {
      id: 'bea-pce-2026-11-25',
      kind: 'pce',
      at: '2026-11-25T13:30:00Z',
      precision: 'exact',
      title: 'Inflation PCE et revenus des ménages',
      detail: 'La mesure d’inflation que la Fed regarde en priorité',
      tier: 'major',
      source: 'bea',
      url: 'https://www.bea.gov/data/income-saving/personal-income',
    },
    {
      id: 'eurostat-hicp-flash-2026-12-01',
      kind: 'hicp',
      at: '2026-12-01T14:00:00Z',
      precision: 'exact',
      title: 'Inflation zone euro (estimation rapide)',
      detail: 'IPCH, première estimation',
      tier: 'major',
      source: 'eurostat',
      url: 'https://www.ecb.europa.eu/press/calendars/statscal/ges/html/sthicp.en.html',
    },
    {
      id: 'bls-jolts-2026-12-01',
      kind: 'jolts',
      at: '2026-12-01T15:00:00Z',
      precision: 'exact',
      title: 'Postes vacants (JOLTS)',
      detail: 'Données d’octobre 2026',
      tier: 'secondary',
      source: 'bls',
      url: 'https://www.bls.gov/schedule/news_release/jolts.htm',
    },
    {
      id: 'bls-employment-2026-12-04',
      kind: 'employment',
      at: '2026-12-04T13:30:00Z',
      precision: 'exact',
      title: 'Emploi américain (rapport mensuel)',
      detail: 'Données de novembre 2026',
      tier: 'major',
      source: 'bls',
      url: 'https://www.bls.gov/schedule/news_release/empsit.htm',
    },
    {
      id: 'fomc-decision-2026-12-09',
      kind: 'fomc-decision',
      at: '2026-12-09T19:00:00Z',
      precision: 'exact',
      title: 'Décision de la Fed (FOMC)',
      detail: 'Communiqué, conférence de presse et projections économiques',
      tier: 'major',
      source: 'fomc',
      url: 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
    },
    {
      id: 'bls-cpi-2026-12-10',
      kind: 'cpi',
      at: '2026-12-10T13:30:00Z',
      precision: 'exact',
      title: 'Inflation américaine (CPI)',
      detail: 'Données de novembre 2026',
      tier: 'major',
      source: 'bls',
      url: 'https://www.bls.gov/schedule/news_release/cpi.htm',
    },
    {
      id: 'bls-ppi-2026-12-15',
      kind: 'ppi',
      at: '2026-12-15T13:30:00Z',
      precision: 'exact',
      title: 'Prix à la production (PPI)',
      detail: 'Données de novembre 2026',
      tier: 'secondary',
      source: 'bls',
      url: 'https://www.bls.gov/schedule/news_release/ppi.htm',
    },
    {
      id: 'eurostat-hicp-final-2026-12-17',
      kind: 'hicp',
      at: '2026-12-17T11:00:00Z',
      precision: 'exact',
      title: 'Inflation zone euro (définitif)',
      detail: 'IPCH, chiffre révisé',
      tier: 'secondary',
      source: 'eurostat',
      url: 'https://www.ecb.europa.eu/press/calendars/statscal/ges/html/sthicp.en.html',
    },
    {
      id: 'ecb-decision-2026-12-17',
      kind: 'ecb-decision',
      at: '2026-12-17T13:15:00Z',
      precision: 'day',
      title: 'Décision de la BCE (Conseil des gouverneurs)',
      detail: 'Communiqué puis conférence de presse',
      tier: 'major',
      source: 'ecb',
      url: 'https://www.ecb.europa.eu/press/calendars/mgcgc/html/index.en.html',
    },
    {
      id: 'bea-gdp-2026-12-23',
      kind: 'gdp',
      at: '2026-12-23T13:30:00Z',
      precision: 'exact',
      title: 'PIB américain',
      tier: 'major',
      source: 'bea',
      url: 'https://www.bea.gov/data/gdp/gross-domestic-product',
    },
    {
      id: 'bea-pce-2026-12-23',
      kind: 'pce',
      at: '2026-12-23T13:30:00Z',
      precision: 'exact',
      title: 'Inflation PCE et revenus des ménages',
      detail: 'La mesure d’inflation que la Fed regarde en priorité',
      tier: 'major',
      source: 'bea',
      url: 'https://www.bea.gov/data/income-saving/personal-income',
    },
    {
      id: 'eurostat-hicp-flash-2027-01-06',
      kind: 'hicp',
      at: '2027-01-06T14:00:00Z',
      precision: 'exact',
      title: 'Inflation zone euro (estimation rapide)',
      detail: 'IPCH, première estimation',
      tier: 'major',
      source: 'eurostat',
      url: 'https://www.ecb.europa.eu/press/calendars/statscal/ges/html/sthicp.en.html',
    },
    {
      id: 'eurostat-hicp-final-2027-01-19',
      kind: 'hicp',
      at: '2027-01-19T11:00:00Z',
      precision: 'exact',
      title: 'Inflation zone euro (définitif)',
      detail: 'IPCH, chiffre révisé',
      tier: 'secondary',
      source: 'eurostat',
      url: 'https://www.ecb.europa.eu/press/calendars/statscal/ges/html/sthicp.en.html',
    },
    {
      id: 'fomc-decision-2027-01-27',
      kind: 'fomc-decision',
      at: '2027-01-27T19:00:00Z',
      precision: 'exact',
      title: 'Décision de la Fed (FOMC)',
      detail: 'Communiqué et conférence de presse',
      tier: 'major',
      source: 'fomc',
      url: 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
    },
    {
      id: 'ecb-decision-2027-02-04',
      kind: 'ecb-decision',
      at: '2027-02-04T13:15:00Z',
      precision: 'day',
      title: 'Décision de la BCE (Conseil des gouverneurs)',
      detail: 'Communiqué puis conférence de presse',
      tier: 'major',
      source: 'ecb',
      url: 'https://www.ecb.europa.eu/press/calendars/mgcgc/html/index.en.html',
    },
    {
      id: 'fomc-decision-2027-03-17',
      kind: 'fomc-decision',
      at: '2027-03-17T18:00:00Z',
      precision: 'exact',
      title: 'Décision de la Fed (FOMC)',
      detail: 'Communiqué, conférence de presse et projections économiques',
      tier: 'major',
      source: 'fomc',
      url: 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
    },
    {
      id: 'ecb-decision-2027-03-18',
      kind: 'ecb-decision',
      at: '2027-03-18T13:15:00Z',
      precision: 'day',
      title: 'Décision de la BCE (Conseil des gouverneurs)',
      detail: 'Communiqué puis conférence de presse',
      tier: 'major',
      source: 'ecb',
      url: 'https://www.ecb.europa.eu/press/calendars/mgcgc/html/index.en.html',
    },
    {
      id: 'fomc-decision-2027-04-28',
      kind: 'fomc-decision',
      at: '2027-04-28T18:00:00Z',
      precision: 'exact',
      title: 'Décision de la Fed (FOMC)',
      detail: 'Communiqué et conférence de presse',
      tier: 'major',
      source: 'fomc',
      url: 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
    },
    {
      id: 'ecb-decision-2027-04-29',
      kind: 'ecb-decision',
      at: '2027-04-29T12:15:00Z',
      precision: 'day',
      title: 'Décision de la BCE (Conseil des gouverneurs)',
      detail: 'Communiqué puis conférence de presse',
      tier: 'major',
      source: 'ecb',
      url: 'https://www.ecb.europa.eu/press/calendars/mgcgc/html/index.en.html',
    },
    {
      id: 'fomc-decision-2027-06-09',
      kind: 'fomc-decision',
      at: '2027-06-09T18:00:00Z',
      precision: 'exact',
      title: 'Décision de la Fed (FOMC)',
      detail: 'Communiqué, conférence de presse et projections économiques',
      tier: 'major',
      source: 'fomc',
      url: 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
    },
    {
      id: 'ecb-decision-2027-06-10',
      kind: 'ecb-decision',
      at: '2027-06-10T12:15:00Z',
      precision: 'day',
      title: 'Décision de la BCE (Conseil des gouverneurs)',
      detail: 'Communiqué puis conférence de presse',
      tier: 'major',
      source: 'ecb',
      url: 'https://www.ecb.europa.eu/press/calendars/mgcgc/html/index.en.html',
    },
    {
      id: 'ecb-decision-2027-07-22',
      kind: 'ecb-decision',
      at: '2027-07-22T12:15:00Z',
      precision: 'day',
      title: 'Décision de la BCE (Conseil des gouverneurs)',
      detail: 'Communiqué puis conférence de presse',
      tier: 'major',
      source: 'ecb',
      url: 'https://www.ecb.europa.eu/press/calendars/mgcgc/html/index.en.html',
    },
    {
      id: 'fomc-decision-2027-07-28',
      kind: 'fomc-decision',
      at: '2027-07-28T18:00:00Z',
      precision: 'exact',
      title: 'Décision de la Fed (FOMC)',
      detail: 'Communiqué et conférence de presse',
      tier: 'major',
      source: 'fomc',
      url: 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
    },
    {
      id: 'ecb-decision-2027-09-09',
      kind: 'ecb-decision',
      at: '2027-09-09T12:15:00Z',
      precision: 'day',
      title: 'Décision de la BCE (Conseil des gouverneurs)',
      detail: 'Communiqué puis conférence de presse',
      tier: 'major',
      source: 'ecb',
      url: 'https://www.ecb.europa.eu/press/calendars/mgcgc/html/index.en.html',
    },
    {
      id: 'fomc-decision-2027-09-15',
      kind: 'fomc-decision',
      at: '2027-09-15T18:00:00Z',
      precision: 'exact',
      title: 'Décision de la Fed (FOMC)',
      detail: 'Communiqué, conférence de presse et projections économiques',
      tier: 'major',
      source: 'fomc',
      url: 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
    },
    {
      id: 'fomc-decision-2027-10-27',
      kind: 'fomc-decision',
      at: '2027-10-27T18:00:00Z',
      precision: 'exact',
      title: 'Décision de la Fed (FOMC)',
      detail: 'Communiqué et conférence de presse',
      tier: 'major',
      source: 'fomc',
      url: 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
    },
    {
      id: 'ecb-decision-2027-10-28',
      kind: 'ecb-decision',
      at: '2027-10-28T12:15:00Z',
      precision: 'day',
      title: 'Décision de la BCE (Conseil des gouverneurs)',
      detail: 'Communiqué puis conférence de presse',
      tier: 'major',
      source: 'ecb',
      url: 'https://www.ecb.europa.eu/press/calendars/mgcgc/html/index.en.html',
    },
    {
      id: 'fomc-decision-2027-12-08',
      kind: 'fomc-decision',
      at: '2027-12-08T19:00:00Z',
      precision: 'exact',
      title: 'Décision de la Fed (FOMC)',
      detail: 'Communiqué, conférence de presse et projections économiques',
      tier: 'major',
      source: 'fomc',
      url: 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
    },
    {
      id: 'ecb-decision-2027-12-16',
      kind: 'ecb-decision',
      at: '2027-12-16T13:15:00Z',
      precision: 'day',
      title: 'Décision de la BCE (Conseil des gouverneurs)',
      detail: 'Communiqué puis conférence de presse',
      tier: 'major',
      source: 'ecb',
      url: 'https://www.ecb.europa.eu/press/calendars/mgcgc/html/index.en.html',
    },
    {
      id: 'ecb-decision-2028-02-03',
      kind: 'ecb-decision',
      at: '2028-02-03T13:15:00Z',
      precision: 'day',
      title: 'Décision de la BCE (Conseil des gouverneurs)',
      detail: 'Communiqué puis conférence de presse',
      tier: 'major',
      source: 'ecb',
      url: 'https://www.ecb.europa.eu/press/calendars/mgcgc/html/index.en.html',
    },
    {
      id: 'ecb-decision-2028-03-23',
      kind: 'ecb-decision',
      at: '2028-03-23T13:15:00Z',
      precision: 'day',
      title: 'Décision de la BCE (Conseil des gouverneurs)',
      detail: 'Communiqué puis conférence de presse',
      tier: 'major',
      source: 'ecb',
      url: 'https://www.ecb.europa.eu/press/calendars/mgcgc/html/index.en.html',
    },
    {
      id: 'ecb-decision-2028-05-04',
      kind: 'ecb-decision',
      at: '2028-05-04T12:15:00Z',
      precision: 'day',
      title: 'Décision de la BCE (Conseil des gouverneurs)',
      detail: 'Communiqué puis conférence de presse',
      tier: 'major',
      source: 'ecb',
      url: 'https://www.ecb.europa.eu/press/calendars/mgcgc/html/index.en.html',
    },
    {
      id: 'ecb-decision-2028-06-08',
      kind: 'ecb-decision',
      at: '2028-06-08T12:15:00Z',
      precision: 'day',
      title: 'Décision de la BCE (Conseil des gouverneurs)',
      detail: 'Communiqué puis conférence de presse',
      tier: 'major',
      source: 'ecb',
      url: 'https://www.ecb.europa.eu/press/calendars/mgcgc/html/index.en.html',
    },
    {
      id: 'ecb-decision-2028-07-20',
      kind: 'ecb-decision',
      at: '2028-07-20T12:15:00Z',
      precision: 'day',
      title: 'Décision de la BCE (Conseil des gouverneurs)',
      detail: 'Communiqué puis conférence de presse',
      tier: 'major',
      source: 'ecb',
      url: 'https://www.ecb.europa.eu/press/calendars/mgcgc/html/index.en.html',
    },
    {
      id: 'ecb-decision-2028-09-07',
      kind: 'ecb-decision',
      at: '2028-09-07T12:15:00Z',
      precision: 'day',
      title: 'Décision de la BCE (Conseil des gouverneurs)',
      detail: 'Communiqué puis conférence de presse',
      tier: 'major',
      source: 'ecb',
      url: 'https://www.ecb.europa.eu/press/calendars/mgcgc/html/index.en.html',
    },
    {
      id: 'ecb-decision-2028-10-12',
      kind: 'ecb-decision',
      at: '2028-10-12T12:15:00Z',
      precision: 'day',
      title: 'Décision de la BCE (Conseil des gouverneurs)',
      detail: 'Communiqué puis conférence de presse',
      tier: 'major',
      source: 'ecb',
      url: 'https://www.ecb.europa.eu/press/calendars/mgcgc/html/index.en.html',
    },
    {
      id: 'ecb-decision-2028-12-07',
      kind: 'ecb-decision',
      at: '2028-12-07T13:15:00Z',
      precision: 'day',
      title: 'Décision de la BCE (Conseil des gouverneurs)',
      detail: 'Communiqué puis conférence de presse',
      tier: 'major',
      source: 'ecb',
      url: 'https://www.ecb.europa.eu/press/calendars/mgcgc/html/index.en.html',
    },
  ],
};
